#-------------------------------------------------------------------------------
# Dockerfile for cross-compiling the Ethereum C++ components for mobile Linux
# platforms such as Tizen, Sailfish and Ubuntu Touch.  Assumes that we have
# previous built the cross-compiler and can just copy that into our
# container.
#
# See http://ethereum.org/ to learn more about Ethereum.
# See http://doublethink.co/ to learn more about doublethinkco
#
# (c) 2015 Kitsilano Software Inc
#-------------------------------------------------------------------------------

FROM ubuntu:14.04
MAINTAINER Bob Summerwill <bob@summerwill.net>

# We need to use an extra PPA (Personal Package Archive) for CMake 3.x
# builds.   The package archive for the Ubuntu Trusty (14.04) image only
# comes with CMake 2.8.x, which is not new enough to build Ethereum
#
# See https://launchpad.net/~george-edison55/+archive/ubuntu/cmake-3.x
# for more details on this archive.
RUN apt-get install software-properties-common
RUN add-apt-repository ppa:george-edison55/cmake-3.x
RUN apt-get update

# External packages required by our scripts
RUN apt-get install -y \
  bzip2=1.0.6-5 \
  cmake \
    git=1:1.9.1-1ubuntu0.1 \
     m4=1.4.17-2ubuntu1
   tree=1.6.0-1 \
  unzip=6.0-9ubuntu1.5 \
   wget=1.15-1ubuntu1.14.04.1

# Switch to a normal user account.  crosstool-ng refuses to run as root.
RUN useradd -ms /bin/bash xcompiler
USER xcompiler

# Clone the sandbox repo into the docker container, including sub-modules
WORKDIR /home/xcompiler
RUN git clone --recursive https://github.com/doublethinkco/webthree-umbrella.git

# wget, untar and unzip the prebuilt cross-compiler.  Ignore non-zero return
# code error caused by HTTPS re-direct to CDN.
RUN wget ‐‐output-document=x-tools.tar.gz https://github.com/doublethinkco/webthree-umbrella-cross/releases/download/0.0.2/x-tools.tar.gz; exit 0
RUN tar xvfz x-tools.tar.gz

# Use that cross-compiler to build the ARM executable
WORKDIR /home/xcompiler/webthree-umbrella/cross-build/ethereum
RUN ./main.sh ~/x-tools/arm-unknown-linux-gnueabi
