#-------------------------------------------------------------------------------
# Dockerfile for cross-compiling the Ethereum C++ components for mobile Linux
# platforms such as Tizen, Sailfish and Ubuntu Touch.  Assumes that we have
# previous built the cross-compiler and can just copy that into our
# container.
#
# TARGET_ARCHITECTURE is an environment variable used to parameterize this
# process.
#
# See http://ethereum.org/ to learn more about Ethereum.
# See http://doublethink.co/ to learn more about doublethinkco
#
# (c) 2015 Kitsilano Software Inc
#-------------------------------------------------------------------------------

FROM ubuntu:14.04
MAINTAINER Bob Summerwill <bob@summerwill.net>

# Target architecture for cross-build.  This default corresponds to 'armel'.
ENV TARGET_ARCHITECTURE "arm-unknown-lincrux-gnueabi"

# We need to use an extra PPA (Personal Package Archive) for CMake 3.x
# builds.   The package archive for the Ubuntu Trusty (14.04) image only
# comes with CMake 2.8.x, which is not new enough to build Ethereum
#
# See https://launchpad.net/~george-edison55/+archive/ubuntu/cmake-3.x
# for more details on this archive.
RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:george-edison55/cmake-3.x

# External packages required by our scripts
RUN apt-get update && apt-get install -y \
  autoconf \
  bzip2=1.0.6-5 \
  cmake=3.2.2-2ubuntu2~ubuntu14.04.1~ppa1 \
    git=1:1.9.1-1ubuntu0.2 \
     m4=1.4.17-2ubuntu1 \
   tree=1.6.0-1 \
  unzip=6.0-9ubuntu1.5 \
   wget=1.15-1ubuntu1.14.04.1

# Install "official" armel and armhf cross-compiler packages, which
# can be used as an alternative to our own custom crosstool-NG toolchains.
RUN apt-get update && apt-get install -y \
    g++-arm-linux-gnueabi=4:4.7.2-1 \
  g++-arm-linux-gnueabihf=4:4.8.2-1

# Switch to a normal user account.
RUN useradd -ms /bin/bash crosseth
USER crosseth

# Clone the webthree-umbrella repo into the docker container, including sub-modules
WORKDIR /home/crosseth
RUN git clone --recursive https://github.com/ethereum/webthree-umbrella.git

# Copy our cross-building scripts into the container
ADD cross-build/ /home/crosseth/webthree-umbrella/cross-build/

# And switch the working directory to the Ethereum cross-build scripts
WORKDIR /home/crosseth/webthree-umbrella/cross-build/ethereum
